TinyBlog/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin
admin.autodiscover()

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
from TinyBlog import views

urlpatterns = patterns('',
    # Examples:
    url(r'^$', views.index),
    # url(r'^TinyBlog/', include('TinyBlog.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/',include('users.urls', namespace='users')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
)

blog/urls.py
from django.conf.urls import patterns, include, url

from blog import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'TinyBlog.views.home', name='home'),
    # url(r'^TinyBlog/', include('TinyBlog.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^create/$', views.new_post, name='new_post'),
)

users/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
from users import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'TinyBlog.views.home', name='home'),
    # url(r'^TinyBlog/', include('TinyBlog.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^create/$', views.create, name = 'create'),
    url(r'^login/$', views.login, name = 'login'),
)

blog/models.py
import datetime

from django.db import models
from django import forms

#import user
from users.models import User

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User)
    content = models.CharField(max_length=140)
    write_time = models.DateTimeField(default=datetime.datetime.now)
    
    def __unicode__(self):
        return '[' + self.content + ']'

class Comment(models.Model):
    author = models.ForeignKey(User)
    content = models.CharField(max_length=140)
    write_time = models.DateTimeField(default=datetime.datetime.now)
    post_id = models.ForeignKey(Post)
    
    def __unicode__(self):
        return '[' + self.content + ']'

users/models.py
from django.db import models
from django import forms

# Create your models here.
class User(models.Model):
    email = models.EmailField(max_length=100)
    genders = models.IntegerField(default=0, blank=True)
    birth_date = models.DateField(null=True)
    password = models.CharField(max_length=100)
    nick_name = models.CharField(max_length=30)
    full_name = models.CharField(max_length=30)
    following = models.ManyToManyField('self', symmetrical=False)
    
    def __unicode__(self):
        return "Nick Name: %s, Id: %s" % (self.nick_name, self.id)

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ['full_name', 'nick_name', 'password', 'email']

TinyBlog/views.py
from django.shortcuts import render, redirect

def index(request):
    user_id = request.session.get('user_id')
    print request.session.get('nick_name')
    if not user_id:
        return render(request,'login.html')
    else:
        return render(request,'index.html', {"nick_name":request.session.get('nick_name')})

blog/views.py
# Create your views here.
from django.shortcuts import get_object_or_404
from django.http import HttpResponse

from users.models import User
from blog.models import Post

def new_post(request):
    author_id = request.session._author_id
    user = get_object_or_404(User,id=author_id)
    post = Post(author = user, content=request.POST['content'])
    post.save()
    return HttpResponse('Create new post successfully')

users/views.py
# Create your views here.
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils import simplejson as sjson

from users.models import UserForm
from users.models import User

def signup(request):
    form = UserForm()
    return render(request,'users/new-signup.html', {'form':form})

def login(request):
    user_mail = request.POST['email']
    password = request.POST['password']
    try:
        login_user = User.objects.get(email=user_mail)
        if login_user:
            request.session['nick_name'] = login_user.nick_name
            request.session['email'] = login_user.email 
            request.session['user_id'] = login_user.id
            return redirect('/')
        else:
            return render(request,'login.html', {'error':"Password not correct!"})
    except User.DoesNotExist:
        return render(request, 'login.html', {'error':"User not exist!"})

def create(request):
    user = UserForm(request.POST)
    if user.is_valid():
        user.save()
        return HttpResponse("Successfully create new account")
    else:
        return HttpResponse("Your input data is not valid </br>" + str(user._errors))

TinyBlog/templates/home.html
{% extends "base_site.html" %}
{% block content %}
<div class="welcome fluid">
  <div class="row">
    <div class="left">
      Welcome
    </div>
    <div class="right">
      <div class="row">
        <form action="{% url 'user:login' %}" method="POST">
	  <div class="col-lg-10">
            <input class="form-control" type="text" placeholder="Your email address"/>
          </div>
          <div class="col-lg-10">
            <input class="form-control" type="password" id="signin-password" placeholder="Password" id="password"/>
            <button class="btn btn-primary submit" type="submit">
	      Sign in
            </button>
          </div>
        </form>
      </div>
      <div class="row form-signup">
        <form class="form-horizontal" role="form">
           <h2>
              <strong>New to TinyBlog?</strong>Sign Up
	   </h2>
          <div class="col-lg-10">
            <input type="text" class="form-control" name="full-name" placeholder="Full name"/>
          </div>
          <div class="col-lg-10">
            <input type="text" class="form-control" name="email" placeholder="Email address"/>
          </div>
          <div class="col-lg-10">
            <input type="password" id="signup-password" class="form-control" name="password" placeholder="Password"/>
          </div>
          <div class="col-lg-10">
            <button class="btn btn-primary btn-signup" class="form-control" type="submit">
	      Sign up TinyBlog
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

TinyBlog/templates/index.html
{% extends "base_site.html" %}
{% block extra %}
<div class="navbar-right navbar-header user-info">
  <span class="user-image icon-bar"></span>
  <a class="navbar-brand" href="#">{{  nick_name }}</a>
</div>
{% endblock %}

TinyBlog/templates/login.html
{% extends 'base_form.html' %}
{% block error_msg %}
<strong>Sign in failed: </strong> {{error}}
{% endblock %}
{% block center_form %}
<h1>Sign in TinyBlog</h1>
<form class="form-horizontal login-form" role="form" action="{% url 'users:login' %}" method="post">
  {% csrf_token %}
  <div class="form-group">
    <label class="col-lg-2 control-label" for="inputEmail">
      Email
    </label>
    <div class="col-lg-7">
      <input class="form-control" type="email" name="email" placeholder="Email" id="inputEmail"/>
    </div>
  </div>
  <div class="form-group">
    <label class="col-lg-2 control-label" for="inputPassword1" id="inputPassLabel">
      Password
    </label>
    <div class="col-lg-7 pass-group">
      <input class="form-control" type="password" name="password" placeholder="Password" id="inputPassword"/>
      <span class="help-block">Forgot your <a>password?</a></span>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-5">
      <button class="btn btn-primary" type="submit">
	Sign in
      </button>
    </div>
  </div>
</form>
{% endblock %}
{% block extra_info %}
  <div class="signup-wrapper">
     <div class="signup-pan">
       <strong>New to TinyBlog?</strong>
       <a href="{% url 'users:signup' %}">Sign up now</a>
     </div>
  </div>
</div>
{% endblock %}

templates/base_form.html
{% extends 'base_site.html' %}
{% block content %}
{% block error_block %}
<div class="alert alert-danger alter-dismissable error-info" style="margin:0 10%;{% if error %}display:block;{% else %}display:none;{% endif %}">
   <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
   {% block error_msg %}{% endblock %}
</div>
{% endblock %}
<div class="form-container">
   <div class="signin-pan">
     {% block center_form %}
     {% endblock %}
  </div>
  {% block extra_info %}
  {% endblock %}
</div>
{% endblock %}

templates/base_site.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}Tiny Blog{% endblock %}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'bs/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/app.css' %}" rel="stylesheet">
    {% block css %}{% endblock %}
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="{% static 'bs/js/html5shiv.js' %}"></script>
      <script src="{% static 'bs/js/respond.min.js' %}"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container header">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Tiny Blog</a>
        </div>
	{% block extra %}{% endblock %}
      </div>
    </div>
    <div class="container body">
      {% block content %}{% endblock %}
    </div>
    <script src="{% static 'jquery/jquery.js' %}"></script>
    <script src="{% static 'bs/js/bootstrap.min.js'%}"></script>
    {% block js %}{% endblock %}
  </body>
</html>

users/templates/users/new-signup.html
{% extends 'base_form.html' %}
{% block center_form %}
<form class="form-horizontal signup-form" action="{% url 'users:create' %}" method="POST">
  <h1>Sing up to TinyBlog</h1>
  <div class="form-group">
      <label class="col-lg-4 control-label" for="Full Name">
	Full Name
      </label>
      <div class="col-lg-7">
          <input class="form-control" type="text" placeholder="Full Name" name="full_name"/>
      </div>
  </div>
  <div class="form-group">
      <label class="col-lg-4 control-label" for="Nick Name">
	Nick Name
      </label>
      <div class="col-lg-7">
          <input class="form-control" type="text" placeholder="Nick Name" name="nick_name"/>
      </div>
  </div>
  <div class="form-group">
      <label class="col-lg-4 control-label" for="Email">
	Email
      </label>
      <div class="col-lg-7">
          <input class="form-control" type="text" placeholder="Email" name="email"/>
      </div>
  </div>
  <div class="form-group">
      <label class="col-lg-4 control-label" for="Password">
	Password
      </label>
      <div class="col-lg-7">
          <input class="form-control" type="password" name="password" placeholder="Password"/>
      </div>
  </div>
  <div class="form-group">
     <div class="col-lg-offset-4 col-lg-5">
       <button class="btn btn-primary" type="submit">
	 Sign up
       </button>
     </div>
  </div>
</form>
{% endblock %}

users/templates/users/signup.html
<form method="post" action="{% url 'add' %}">
  {% csrf_token %}
  <div>
    <label>
      Full name
    </label>
    <input type="text" name="full_name"/>
  </div>
  <div>
    <label>
      Email address
    </label>
    <input type="text" name="email"/>
  </div>
  <div>
      <label>
	Create a password
      </label>
      <input type="password" name="password"/>
  </div>
  <div>
      <label>
	Choose your username
      </label>
      <input type="text" name="nick_name"/>
  </div>
  <div>
    <input type="submit" value="Create my account"/>
  </div>
</form>